services:
  app:
    build: .
    command: python app.py
    volumes:
      - .:/app
      - app_data:/var/lib/app
      - chrome_driver_cache:/root/.wdm
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"

  db:
    image: postgres:16.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data:
  app_data:
  chrome_driver_cache:
