services:
  app:
    # build: .
    image: metehangnn/techeventradar:latest
    container_name: techeventradar_app
    restart: always
    env_file:
      - .env
    volumes:
      - eventradar_sock:/home/meto/TechEventRadar/eventradar.sock
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:16.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data:
  app_data:
  chrome_driver_cache:
